/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vue;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle.ComponentPlacement;

import dao.InterService;
import dao.UserService;
import model.User;

import javax.swing.JButton;
import javax.swing.JDialog;

import java.awt.SystemColor;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.awt.event.ActionEvent;
import java.awt.Color;
import java.awt.Font;
import javax.swing.SwingConstants;

/**
 *
 * @author ANOUSSI
 */
public class AddNewSoldeClient extends javax.swing.JDialog {
    User user;
    public InterService serVice = new UserService();
    private DialogCallback dialogCallback;
    public DialogCallback getDialogCallback() {
		return dialogCallback;
	}

	public void setDialogCallback(DialogCallback dialogCallback) {
		this.dialogCallback = dialogCallback;
	}

    /**
     * Creates new form AddNewSoldeClient
     */
    public AddNewSoldeClient(JDialog parent, User user) {
    	super(parent, "FC", true);
        this.user=user;
        initComponents(); 
        jTextNomClient.setText(user.getName());
        jTextnewSolde.setText(String.valueOf(user.getSolde()));
        textFieldPrenom.setText(user.getPrenom());
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(SystemColor.textHighlight);
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBackground(SystemColor.textHighlight);
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Times New Roman", Font.BOLD, 16));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Times New Roman", Font.BOLD, 16));
        jTextNomClient = new javax.swing.JTextField();
        jTextNomClient.setForeground(Color.GREEN);
        jTextNomClient.setFont(new Font("Times New Roman", Font.BOLD, 18));
        jTextnewSolde = new javax.swing.JTextField();
        jTextnewSolde.setFont(new Font("Times New Roman", Font.BOLD, 25));
        jTextnewSolde.setHorizontalAlignment(SwingConstants.CENTER);
        jTextnewSolde.setForeground(new Color(220, 20, 60));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        /////////////////////insertion du icon
        
        String imagePath = ("depot.png");

        int desiredWidth = 300;
        int desiredHeight = 150;
       // BufferedImage resizedImage =FrameConnexion.resizeImage(imagePath, desiredWidth, desiredHeight);
     //   ImageIcon icon = new ImageIcon(resizedImage);
        
        
        
        JLabel lblNewLabel = new JLabel("CREDITER LE SOLDE COURANT DU CLIENT");
     //   JLabel lblNewLabel = new JLabel("CREDITER LE SOLDE COURANT DU CLIENT",icon, JLabel.LEFT);
        lblNewLabel.setFont(new Font("Times New Roman", Font.BOLD, 16));
        lblNewLabel.setForeground(Color.WHITE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(lblNewLabel, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
        );
        jPanel1.setLayout(jPanel1Layout);
        
        btnNewButtonCancel = new JButton("Cancel");
        btnNewButtonCancel.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        	}
        });
        
        btnNewButtonOK = new JButton("OK");
        btnNewButtonOK.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		User userUpdate=new User();
        		userUpdate.setId(user.getId());
        		userUpdate.setPrenom(textFieldPrenom.getText() );
        		userUpdate.setName( jTextNomClient.getText() );
        		userUpdate.setSolde(Integer.valueOf(jTextnewSolde.getText().toString()));
        		boolean fait=serVice.updateUser(userUpdate);
        		if(fait) {
        			dialogCallback.actualiser(1);
        			JOptionPane.showMessageDialog(null, " Opertion terminer  \n Merci!");
        		}else {
        			JOptionPane.showMessageDialog(null, " non fait \n Merci!");
        		}
        		dispose();
        		
        		
        	}
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(351, Short.MAX_VALUE)
        			.addComponent(btnNewButtonOK)
        			.addGap(36)
        			.addComponent(btnNewButtonCancel)
        			.addGap(36))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(32, Short.MAX_VALUE)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnNewButtonCancel)
        				.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        					.addComponent(btnNewButtonOK)
        					.addContainerGap())))
        );
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setText("Nom du Client");

        jLabel2.setText("Nouveau Solde du Client");
        
        JLabel lblPrenom = new JLabel("Prenom");
        lblPrenom.setFont(new Font("Times New Roman", Font.BOLD, 16));
        
        textFieldPrenom = new JTextField();
        textFieldPrenom.setFont(new Font("Times New Roman", Font.BOLD, 18));
        textFieldPrenom.setForeground(Color.GREEN);
        textFieldPrenom.setColumns(10);
        
        lblNewLabel_1 = new JLabel("XAF");
        lblNewLabel_1.setFont(new Font("Times New Roman", Font.BOLD, 18));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 162, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(lblPrenom, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jLabel2)))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(textFieldPrenom, GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        						.addComponent(jTextNomClient, GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jTextnewSolde, GroupLayout.PREFERRED_SIZE, 229, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)))))
        			.addContainerGap())
        		.addComponent(jPanel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextNomClient, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textFieldPrenom, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblPrenom))
        			.addGap(36)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextnewSolde, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2)
        				.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
        			.addGap(26)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewSoldeClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewSoldeClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewSoldeClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewSoldeClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextNomClient;
    private javax.swing.JTextField jTextnewSolde;
    private JButton btnNewButtonCancel;
    private JButton btnNewButtonOK;
    private JTextField textFieldPrenom;
    private JLabel lblNewLabel_1;
}
