/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vue;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JPanel;

import java.awt.Frame;
import java.awt.SystemColor;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import Global.GlobalVar;
import dao.InterService;
import dao.UserService;
import model.Fournisseurs;
import model.Statistique;
import model.User;

import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.awt.event.ActionEvent;
import com.toedter.calendar.JDateChooser;
import java.awt.Font;
import java.awt.Color;
import javax.swing.SwingConstants;

/**
 *
 * @author ANOUSSI
 */
public class FrameActivite extends javax.swing.JDialog {
	public InterService serVice = new UserService();
	private DialogCallback dialogCallback;
	GlobalVar globalVar;
	JDateChooser dateChooser;
    JDateChooser dateChooser_1;
    List<Statistique>list;
    JLabel labelVentes;
    JLabel labelMtnCaisse;
 
    JLabel lblNewLabeImp = new JLabel("");

		//List<Fournisseurs> list= new ArrayList<>();
    public FrameActivite(Frame parent) {
        super(parent,"Dialog", true);   
       
        initComponents();
        actualiserTabeau(list) ;
    }
    public DialogCallback getDialogCallback() {
		return dialogCallback;
	}


	public void setDialogCallback(DialogCallback dialogCallback) {
		this.dialogCallback = dialogCallback;
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dateChooser = new JDateChooser();
        dateChooser_1 = new JDateChooser();
         labelVentes = new JLabel("New label");
         labelVentes.setForeground(new Color(0, 51, 153));
         labelVentes.setFont(new Font("Times New Roman", Font.BOLD, 21));
         labelVentes.setHorizontalAlignment(SwingConstants.CENTER);
         labelMtnCaisse = new JLabel("New label");
         labelMtnCaisse.setForeground(new Color(0, 51, 153));
         labelMtnCaisse.setFont(new Font("Times New Roman", Font.BOLD, 21));
         labelMtnCaisse.setHorizontalAlignment(SwingConstants.CENTER);
        
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.MONTH, -1);
        Date lastMonthDate = calendar.getTime();
        Date currentDate=new Date();
    	dateChooser.setDate(lastMonthDate); // D�finir la date minimale	
    	dateChooser_1.setDate(currentDate); // D�finir la date minimale	
    	 list=serVice.getStatisique(lastMonthDate ,currentDate);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        
        JPanel panel = new JPanel();
        panel.setBackground(SystemColor.textHighlight);
        
        JPanel panel_1 = new JPanel();
        panel_1.setBackground(SystemColor.activeCaption);
        
        JPanel panel_3 = new JPanel();
        panel_3.setBackground(SystemColor.activeCaption);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(panel, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(panel_3, GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        			.addContainerGap())
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        			.addGap(31))
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(panel_1, GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(panel_3, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(panel_1, GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
        );
        panel.setLayout(null);
        
        JLabel lblNewLabel_5 = new JLabel("MES STATISTIQUES");
        lblNewLabel_5.setHorizontalAlignment(SwingConstants.CENTER);
        lblNewLabel_5.setForeground(Color.WHITE);
        lblNewLabel_5.setFont(new Font("Times New Roman", Font.PLAIN, 18));
        lblNewLabel_5.setBounds(183, 5, 397, 38);
        panel.add(lblNewLabel_5);
        panel_3.setLayout(null);
        
        
        dateChooser.setBounds(10, 27, 183, 38);
        panel_3.add(dateChooser);
        
        dateChooser_1.setBounds(265, 24, 187, 38);
        panel_3.add(dateChooser_1);
        
        JLabel lblNewLabel_3 = new JLabel("Depuis le :");
        lblNewLabel_3.setFont(new Font("Times New Roman", Font.BOLD, 20));
        lblNewLabel_3.setBounds(24, -1, 169, 24);
        panel_3.add(lblNewLabel_3);
        
        JLabel lblNewLabel_4 = new JLabel("jusqu'au :");
        lblNewLabel_4.setFont(new Font("Times New Roman", Font.BOLD, 20));
        lblNewLabel_4.setBounds(265, -1, 187, 29);
        panel_3.add(lblNewLabel_4);
        
        JButton btnNewButton_1 = new JButton("valider");
        btnNewButton_1.setForeground(Color.WHITE);
        btnNewButton_1.setBackground(new Color(0, 128, 0));
        btnNewButton_1.setFont(new Font("Times New Roman", Font.BOLD, 18));
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		Date lastMonthDate = dateChooser.getDate();
        		Date currentDate = dateChooser_1.getDate();
        		 list=serVice.getStatisique(lastMonthDate ,currentDate);
        		 actualiserTabeau(list) ;
        	}
        });
        btnNewButton_1.setBounds(612, 22, 89, 40);
        panel_3.add(btnNewButton_1);
        panel_1.setLayout(null);
        
        JPanel panel_2 = new JPanel();
        panel_2.setBounds(37, 100, 539, 10);
        panel_1.add(panel_2);
        
        JLabel lblNewLabel = new JLabel("Total des Ventes");
        lblNewLabel.setForeground(new Color(0, 128, 0));
        lblNewLabel.setFont(new Font("Times New Roman", Font.BOLD | Font.ITALIC, 18));
        lblNewLabel.setBounds(23, 11, 127, 19);
        panel_1.add(lblNewLabel);
        
        JLabel lblNewLabel_2 = new JLabel(" Total en caisse");
        lblNewLabel_2.setForeground(new Color(0, 128, 0));
        lblNewLabel_2.setFont(new Font("Times New Roman", Font.BOLD | Font.ITALIC, 18));
        lblNewLabel_2.setBounds(252, 9, 127, 23);
        panel_1.add(lblNewLabel_2);
        
        JButton btnNewButton = new JButton("Cancel");
        btnNewButton.setFont(new Font("Times New Roman", Font.ITALIC, 14));
        btnNewButton.setBounds(628, 52, 119, 23);
        panel_1.add(btnNewButton);
        
       
        labelVentes.setBounds(0, 33, 190, 33);
        panel_1.add(labelVentes);
      
        labelMtnCaisse.setBounds(215, 32, 190, 34);
        panel_1.add(labelMtnCaisse);
        
        JLabel lblNewLabel_1 = new JLabel("total des Impayés");
        lblNewLabel_1.setForeground(new Color(0, 128, 0));
        lblNewLabel_1.setFont(new Font("Times New Roman", Font.BOLD | Font.ITALIC, 18));
        lblNewLabel_1.setBounds(461, 5, 139, 31);
        panel_1.add(lblNewLabel_1);
                lblNewLabeImp.setForeground(new Color(255, 51, 0));
                lblNewLabeImp.setFont(new Font("Times New Roman", Font.BOLD, 21));
                lblNewLabeImp.setHorizontalAlignment(SwingConstants.CENTER);
                lblNewLabeImp.setBackground(Color.BLUE);
        
      
        
                lblNewLabeImp.setBounds(434, 36, 166, 33);
        panel_1.add(lblNewLabeImp);
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        	}
        });
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
	 public void actualiserTabeau( List<Statistique>list) {
		 // list = serVice.getListUser(text);
		
		  Object[][] tableau = new Object[list.size()][6];
			int i = 0;
			System.out.println("__________________________________");
			System.out.println(list.size());
			System.out.println("__________________________________");
			double totalEncaise=0;
			double totalVendu=0;
			
			for (Statistique stat : list) {
				
				tableau[i][0] = stat.getDate();	
				tableau[i][1] = stat.getNom();
				tableau[i][2] = stat.getMontantVendu();	
				tableau[i][3] = stat.getMontantEncaisse();
				tableau[i][4] = stat.getSoldeClient();	
				tableau[i][5] = stat.getSoldeFournisseur();			
				
				totalVendu+=stat.getMontantVendu();
				totalEncaise+=stat.getMontantEncaisse();
				i++;
			}
			
			
			DefaultTableModel model = new DefaultTableModel(tableau, new String[] {"DATE","NOM","MONTANT VENDU","MONTANT EN CAISSE","SOLDE CLIENT","SOLDE FOURNISSEUR"})
			{
	            @Override
	            public Class<?> getColumnClass(int columnIndex) {
	            	return super.getColumnClass(columnIndex);
	            }

	            @Override
	            public boolean isCellEditable(int row, int column) {
	                return column == 0; // Seule la colonne des cases � cocher est �ditable
	            }
	        };
			 jTable1.setModel(model);
		  
			 labelVentes.setText(String.valueOf(totalVendu));
			 labelMtnCaisse.setText(String.valueOf (totalEncaise ));
			 lblNewLabeImp.setText(String.valueOf(totalVendu-totalEncaise));
		  
	  }
	
	 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameActivite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameActivite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameActivite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameActivite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
    
    }
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
}
